// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package db

import (
	"context"
)

const createBlocksTableIfNotExists = `-- name: CreateBlocksTableIfNotExists :exec
CREATE TABLE IF NOT EXISTS blocks (
    height INTEGER NOT NULL,
    hash TEXT NOT NULL,
    previous_hash TEXT NOT NULL,
    timestamp INTEGER NOT NULL,
    nonce INTEGER NOT NULL,
    data TEXT NOT NULL,
    UNIQUE (hash, height)
)
`

func (q *Queries) CreateBlocksTableIfNotExists(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createBlocksTableIfNotExists)
	return err
}

const deleteBlockByHeightAndHash = `-- name: DeleteBlockByHeightAndHash :exec
DELETE FROM blocks WHERE height = ? AND hash = ?
`

type DeleteBlockByHeightAndHashParams struct {
	Height int64
	Hash   string
}

func (q *Queries) DeleteBlockByHeightAndHash(ctx context.Context, arg DeleteBlockByHeightAndHashParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockByHeightAndHash, arg.Height, arg.Hash)
	return err
}

const getAllBlocks = `-- name: GetAllBlocks :many
SELECT height, hash, previous_hash, timestamp, nonce, data FROM blocks ORDER BY height DESC
`

func (q *Queries) GetAllBlocks(ctx context.Context) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getAllBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.PreviousHash,
			&i.Timestamp,
			&i.Nonce,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllBlocksOrderedByHeight = `-- name: GetAllBlocksOrderedByHeight :many
SELECT height, hash, previous_hash, timestamp, nonce, data FROM blocks ORDER BY height ASC
`

func (q *Queries) GetAllBlocksOrderedByHeight(ctx context.Context) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getAllBlocksOrderedByHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.PreviousHash,
			&i.Timestamp,
			&i.Nonce,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockByHash = `-- name: GetBlockByHash :one
SELECT height, hash, previous_hash, timestamp, nonce, data FROM blocks WHERE hash = ?
`

func (q *Queries) GetBlockByHash(ctx context.Context, hash string) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlockByHash, hash)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.PreviousHash,
		&i.Timestamp,
		&i.Nonce,
		&i.Data,
	)
	return i, err
}

const getBlockByHeight = `-- name: GetBlockByHeight :one
SELECT height, hash, previous_hash, timestamp, nonce, data FROM blocks WHERE height = ?
`

func (q *Queries) GetBlockByHeight(ctx context.Context, height int64) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlockByHeight, height)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.PreviousHash,
		&i.Timestamp,
		&i.Nonce,
		&i.Data,
	)
	return i, err
}

const getBlocksLength = `-- name: GetBlocksLength :one
SELECT COUNT(*) as length FROM blocks
`

func (q *Queries) GetBlocksLength(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlocksLength)
	var length int64
	err := row.Scan(&length)
	return length, err
}

const getBlocksWithMinHeight = `-- name: GetBlocksWithMinHeight :many
SELECT height, hash, previous_hash, timestamp, nonce, data FROM blocks WHERE height >= ? ORDER BY height ASC
`

func (q *Queries) GetBlocksWithMinHeight(ctx context.Context, height int64) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksWithMinHeight, height)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Height,
			&i.Hash,
			&i.PreviousHash,
			&i.Timestamp,
			&i.Nonce,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestBlock = `-- name: GetHighestBlock :one
SELECT height, hash, previous_hash, timestamp, nonce, data FROM blocks ORDER BY height DESC LIMIT 1
`

func (q *Queries) GetHighestBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRowContext(ctx, getHighestBlock)
	var i Block
	err := row.Scan(
		&i.Height,
		&i.Hash,
		&i.PreviousHash,
		&i.Timestamp,
		&i.Nonce,
		&i.Data,
	)
	return i, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT OR IGNORE INTO blocks (
    height,
    hash,
    previous_hash,
    timestamp,
    nonce,
    data
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertBlockParams struct {
	Height       int64
	Hash         string
	PreviousHash string
	Timestamp    int64
	Nonce        int64
	Data         string
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertBlock,
		arg.Height,
		arg.Hash,
		arg.PreviousHash,
		arg.Timestamp,
		arg.Nonce,
		arg.Data,
	)
	return err
}
