// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Block struct {
	Height       int64
	Hash         string
	PreviousHash string
	Timestamp    int64
	Nonce        int64
	Difficulty   int64
	Data         string
}
